title: The most awesome title in the history of all titles in the world
author: Henry Latourrette
email: henry.latourrette@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I don't want to talk to bots in here. Too bad :(

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
